apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: prio101/nodeapp:latest   # replace with your Docker Hub image
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
