apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  type: NodePort   # or LoadBalancer
  selector:
    app: nodeapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
