name: Lint the f out it
run-name: Lint the f out it
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting the linting process..."
      - run: npm install
      - run: npm run lint
      - run: echo "Linting process completed."

